name: mypytest

on: push

jobs:
  test-job1:
    name: testing
    runs-on: ubuntu-latest

    steps:
    - name: Checkout demo repo
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Test with pytest
      run: |
        PYTHONPATH=. pytest tests/
    
  test-job2:
    - name: Print Hello world
      run: |
        echo "This my workflow"
        echo "Hellow world"